version: '3'

volumes:
  pg_data_kittygram_production:
  kittygram_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram_production:/var/lib/postgresql/data
  backend:
    image: coolhaxor/kittygram_backend
    env_file: .env
    volumes:
      - kittygram_static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: coolhaxor/kittygram_frontend
    volumes:
      - kittygram_static:/static
    command: cp -r /app/build/. /static/
    
  gateway:
    image: coolhaxor/kittygram_gateway
    env_file: .env
    ports:
      - ${DOCKER_PORTS}
    volumes:
      - kittygram_static:/static
      - media:/media