version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: coolhaxor/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/

  frontend:
    image: coolhaxor/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: coolhaxor/kittygram_gateway
    env_file: .env
    ports:
      - ${DOCKER_PORTS}
    volumes:
      - static:/staticfiles
      - media:/app/media/